name: 👷‍♀️ Build, sign and create installers

on: [push, pull_request]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: RelWithDebInfo
  

jobs:
  build:
    name: 🛠 🍎 📺 Build for macOS & Windows
    runs-on: ${{ matrix.os.runner }}
    
    strategy:
      matrix:
        os:
        - runner: macos-10.15
          name: mac
        - runner: windows-latest
          name: windows

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    # We are creating the ${{runner.workspace}}/build directory to perform the build
    - name: Configure CMake
      working-directory: ${{runner.workspace}}
      run: cmake -S Schrammel_OJD -B ${{runner.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      working-directory: ${{runner.workspace}}/build
      run: cmake --build . --config ${{env.BUILD_TYPE}}

    - name: Upload
      uses: actions/upload-artifact@v2.2.1
      with:
        name: OJD-${{ matrix.os.name }}
        path: |
              ${{runner.workspace}}/build/OJD_artefacts/${{env.BUILD_TYPE}}
              !${{runner.workspace}}/build/OJD_artefacts/${{env.BUILD_TYPE}}/**/*.a
              !${{runner.workspace}}/build/OJD_artefacts/${{env.BUILD_TYPE}}/**/*.lib


  codesign_and_installer_mac:
      name: 📦 🍎 Sign Artefacts and Build Installer for macOS
      runs-on: macos-10.15
      needs: build
      steps:
        - name: Download macOS artifacts from build performed before
          uses: actions/download-artifact@v2
          with: 
            name: OJD-mac

        - name: Did this work?
          run: ls
