name: 👷‍♀️ Build, sign and create installers

on: [push, pull_request]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: RelWithDebInfo
  

jobs:

  # The Matrix job for the compilation itself, executed on all supported OS
  build:
    name: 🛠 🍎 📺 Build for macOS & Windows
    runs-on: ${{ matrix.os.runner }}
    
    strategy:
      matrix:
        os:
        - runner: macos-10.15
          name: mac
        - runner: windows-latest
          name: windows

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    # We are creating the ${{runner.workspace}}/build directory to perform the build
    - name: Configure CMake
      working-directory: ${{ runner.workspace }}
      run: cmake -S Schrammel_OJD -B ${{ runner.workspace }}/build -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}

    - name: Build
      working-directory: ${{ runner.workspace }}/build
      run: cmake --build . --config ${{ env.BUILD_TYPE }}

    - name: Upload build artefacts and installer support files
      uses: actions/upload-artifact@v2.2.1
      with:
        name: OJD-build-output-${{ matrix.os.name }}
        path: |
              ${{ runner.workspace }}/build/OJD_artefacts/${{ env.BUILD_TYPE }}
              !${{ runner.workspace }}/build/OJD_artefacts/${{ env.BUILD_TYPE }}/**/*.a
              !${{ runner.workspace }}/build/OJD_artefacts/${{ env.BUILD_TYPE }}/**/*.lib

    - name: Upload installer support files
      uses: actions/upload-artifact@v2.2.1
      with:
        name: OJD-installer-files-${{ matrix.os.name }}
        path: ${{ runner.workspace }}/Schrammel_OJD/Deployment/${{ matrix.os.name }}



  # The frist macOS specific deployment task that signs the plugins and builds the installer
  codesign_installer_mac:
      name: 📦 🍎 Build installer for macOS
      runs-on: macos-10.15
      needs: build
      steps:
        - name: Download macOS build artefacts from previous job
          uses: actions/download-artifact@v2
          with: 
            name: OJD-build-output-mac

        - name: Download macOS installer files
          uses: actions/download-artifact@v2
          with: 
            name: OJD-installer-files-mac

        - name: What did we download?
          run: ls
          
        - name: Setup temporary keychain and add application signing certificate
          uses: apple-actions/import-codesign-certs@v1
          with: 
            p12-file-base64: ${{ secrets.APPLE_CERTIFICATE_APPLICATION }}
            p12-password: ${{ secrets.APPLE_CERTIFICATE_PW }}

        - name: Codesign AU plugin
          run: codesign -s "${{ secrets.APPLE_DEVELOPER_ID_APPLICATION }}" AU/OJD.component --timestamp

        - name: Codesign VST3 plugin
          run: codesign -s "${{ secrets.APPLE_DEVELOPER_ID_APPLICATION }}" VST3/OJD.vst3 --timestamp

        - name: Upload signed artefacts
          uses: actions/upload-artifact@v2.2.1
          with:
            name: OJD-signed-mac
            path: |
              AU
              VST3

        - name: Download Packages installer build tool
          run: wget http://s.sudre.free.fr/Software/files/Packages.dmg

        - name: Mount Packages image
          run: hdiutil attach Packages.dmg

        - name: Install Packages
          run: sudo installer -pkg /Volumes/Packages\ 1.2.9/Install\ Packages.pkg -target /

        - name: Build installer
          run: packagesbuild Schrammel\ OJD.pkgproj
        
        - name: Upload installer
          uses: actions/upload-artifact@v2.2.1
          with:
            name: OJD-installer-unsigned-mac
            path: OJD/Schrammel\ OJD.pkg

  # The second macOS specific deployment task that signs and notarizes the installer and creates a dmg
  productsign_notarize_mac:
      name: 🔏 🍎 Sign and notarize installer for macOS
      runs-on: macos-10.15
      needs: codesign_installer_mac
      steps:
        - name: Download macOS build artefacts from previous job
          uses: actions/download-artifact@v2
          with: 
            name: OJD-installer-unsigned-mac

        - name: Setup temporary keychain and add installer signing certificate
          uses: apple-actions/import-codesign-certs@v1
          with: 
            p12-file-base64: ${{ secrets.APPLE_CERTIFICATE_INSTALLER }}
            p12-password: ${{ secrets.APPLE_CERTIFICATE_PW }}

        - name: Create folder for signed installer
          run: mkdir OJD-installer-signed

        - name: Sign installer
          run: productsign -s "${{ secrets.APPLE_DEVELOPER_ID_INSTALLER }}" Schrammel\ OJD.pkg OJD-installer-signed/Install\ OJD.pkg
          
        - name: Notarize installer
          run: npx notarize-cli --file OJD-installer-signed/Install\ OJD.pkg --bundle-id io.schrammel.pkg --username ${{ secrets.APPLE_ID }} --password ${{ secrets.APPLE_NOTARIZATION_PW }}

        - name: Create DMG
          run: hdiutil create Install\ OJD.dmg -fs HFS+ -srcfolder OJD-installer-signed -format UDZO -volname Install\ OJD

        - name: Upload DMG
          uses: actions/upload-artifact@v2.2.1
          with:
            name: OJD-installer-mac
            path: Install\ OJD.dmg

  # A side job to delete intermediate artefacts from the run
  delete_temporary_artefacts:
      name: 🧹 Cleanup intermediate artefacts
      runs-on: ubuntu-latest
      needs: codesign_installer_mac
      steps:
        - name: Cleanup
          uses: geekyeggo/delete-artifact@v1
          with:
            name: |
                OJD-build-output-mac
                OJD-installer-files-mac
